import os
import requests
import redis
import json
import re

from requests.packages.urllib3.exceptions import InsecureRequestWarning

# Suppress the InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

#IP of the redis installation
redis_ip = os.environ.get('REDIS_IP', '0.0.0.0')
#Port of the redis installation
redis_port = os.environ.get('REDIS_PORT', 6379)
#Key for the JSON list of all SNPs
redis_list_key = os.environ.get('REDIS_LIST_KEY', 'list_name')
#Prefix for key values generated by this program
redis_key_prefix = os.environ.get('REDIS_KEY_PREFIX', 'prefix')

#The SNP API requires authentication in order to allow access.
#A bearer token is generated at runtime and is used to authenticate subsequent API calls.
def snp_get_bearer_token(snp_ip, username, password):
    #Build the payload for the authentication request to the SNP
    payload = {
        'username': username,
        'password': password
    }
    #Attempt to authenticate
    try:
        #SNPs use self signed certificates by default, need to disable SSL verification
        response = requests.post(f"https://{snp_ip}/api/auth", json=payload, verify=False)
        response.raise_for_status()
        
        #If Bearer is in the response, we assume that a valid token was generated
        if "Bearer" in response.text:
            #We return the raw token stripped of any other info on the line
            return response.text.replace("Bearer ", "")

    #Otherwise, throw an exception
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")

#This gets the uptime data from the SNP, it calls the authentication method every time in order to ensure that it has valid credentials
def snp_get_data(snp_ip, username, password):
    #Generate a bearer token to use for the next API call
    bearer_token = snp_get_bearer_token(snp_ip, username, password)
    
    #Add the bearer token to the request headers
    headers = {
        'Authorization': f'Bearer {bearer_token}',
        'Content-Type': 'application/json'
    }

    #Query the API at the node which has uptime data
    #SNPs use self signed certificates by default, need to disable SSL verification
    response = requests.get(f"https://{snp_ip}/api/console/status", headers=headers, verify=False)

    #Return the full response
    return response.json()

#Helper method to take the datetime format that the SNP spits out and convert it to an integer representing the number of seconds of uptime.
def format_uptime(uptime):
    #Remove the word up from the line
    uptime = uptime.replace("up ", "")
    #Break the line into a list at every comma
    expanded_uptime = uptime.split(', ')
    seconds = 0;
    #Iterate through the list of time units
    for time_unit in expanded_uptime:
        #Find the integer in the list item
        integer = int(re.findall(r'\d+', time_unit)[0])
        #Convert weeks to seconds
        if "week" in time_unit:
            #Add it to the total
            seconds += (integer * 7 * 24 * 60 * 60)
        #Convert days to seconds
        elif "day" in time_unit:
            #Add it to the total
            seconds += (integer * 24 * 60 * 60)
        #Convert hours to seconds
        elif "hour" in time_unit:
            #Add it to the total
            seconds += (integer * 60 * 60)
        #Convert minutes to seconds
        elif "minute" in time_unit:
            #Add it to the total
            seconds += (integer * 60)
    #Return the total seconds of uptime
    return seconds

#Main execution block
def run_task():
    #Connect to Redis
    r = redis.Redis(host=redis_ip, port=redis_port, db=0) 
    #Get the list of SNPs from Redis
    value = r.get(redis_list_key)
    snp_list = json.loads(value.decode('utf-8'))
    #Iterate through all of the SNPs, request the current uptime, format it, then write the uptime into Redis
    for snp in snp_list['Imagine_SNPs']:
        snp_data = snp_get_data(snp['ip-address'], snp['username'], snp['password'])
        print(snp["hostname"], format_uptime(snp_data["data"]["upTime"]))
        r.set(f'{redis_key_prefix}_{snp["hostname"]}', format_uptime(snp_data["data"]["upTime"]))

if __name__ == "__main__":
    run_task()